### ISSUE TITLE
Update output message to say "Hello Signant"

### ISSUE THREAD

**Issue by samuelkola** [samuelkola/HelloWorld#1]
## Description
Update the hello_world.py script to output "Hello Signant" instead of "Hello, World!"

## Changes Required
In `hello_world.py`, update the print statement:
```python
# From
print("Hello, World!")
# To
print("Hello Signant")
```

## Task Checklist
- [ ] Update print statement in hello_world.py
- [ ] Test the updated script
- [ ] Update README.md if it contains example output
